name: Bytebase CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  bytebase-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Bytebase
        id: bytebase-login
        uses: bytebase/login-action@0.0.2
        with:
          bytebase-url: ${{ secrets.BYTEBASE_URL }}
          service-key: ${{ secrets.BYTEBASE_SERVICE_KEY }}
          service-secret: ${{ secrets.BYTEBASE_SERVICE_SECRET }}
      - name: List projects
        run: |
          curl "${{ secrets.BYTEBASE_URL }}/v1/projects" \
            -H 'Authorization: Bearer ${{ steps.bytebase-login.outputs.token }}' \
            -H 'Content-Type: application/json; charset=utf-8'
